### PR TITLE
Create Pradeep.txt

### PR DESCRIPTION
**Pull request by lankamadangit**
Commit propose changes

### CODE REVIEW

**Comment by IssyAusDevOps** [comment]
request approved

**Review by J-Bankz — APPROVED** [review]

**Review by abairecode — APPROVED** [review]

**Review by C0de0ps — APPROVED** [review]

**Review by Harchie — APPROVED** [review]

**Review by Tosein — APPROVED** [review]

**Review by alihassnain5 — APPROVED** [review]

**Review by nkenuo — APPROVED** [review]

**Comment by abairecode** [comment]
Awesome!

**Review by Ludochris001 — APPROVED** [review]
Change approved

**Review by IssyAusDevOps — COMMENTED** [review]
request approved

**Review by pradeepdevops10 — APPROVED** [review]

**Review by Ndobegang — APPROVED** [review]
All done.

**Review by IssyAusDevOps — APPROVED** [review]
approved

**Review by abiona83 — APPROVED** [review]

**Review by PNIke — APPROVED** [review]

**Review by Chukslearn — APPROVED** [review]
Done

**Pull request merged**
